version: "3.9"

x-logging: &default-logging
  options:
    max-size: "5m"
    max-file: "5"
  driver: json-file

networks:
  proxynet:
    # TODO: the network name depends on the project folder (<project-name_>default)
    name: timescaledb_network

services:
##### BEGIN - NATS Service #####
  # nats-server:
  #   profiles:
  #     - all
  #     - nats
  #   image: ${NATS_TAG}
  #   container_name: ${NATS_NAME}
  #   ports:
  #     - "4222:4222"
  #     - "6222:6222"
  #     - "8222:8222"
  #     - "9222:9222"
  #   labels:
  #     - owner=oes
  #     - type=svc
  #   volumes:
  #     # Input(s)
  #     - ../config/nats:/nats/conf:ro
  #     - ../certs:/nats/certs:ro
  #   command: [-c, /nats/conf/nats-server.conf]
  #   logging: *default-logging
  #   networks:
  #     - proxynet
##### END - NATS Service #####

##### BEGIN - Simple Simulator Apps & Services #####
  # simulator-svc:
  #   profiles:
  #     - all
  #     - simulator
  #   depends_on:
  #     - nats-server
  #   image: ${SIMULATOR_SVC_TAG}
  #   container_name: "simulator_svc"
  #   platform: linux/amd64
  #   ports:
  #     - "20000-20060:20000-20060"
  #   labels:
  #     - owner=oes
  #     - type=svc
  #   environment:
  #     - PLATFORM_NODE_IP=${NATS_NAME}
  #     - PLATFORM_NATS_PORT=${NATS_PORT}
  #   volumes:
  #     # Input(s)
  #     - ../config/simulator:/resources:ro
  #   command: ${SIMPLE_SIMULATOR_SVC_CMD}
  #   logging: *default-logging
  #   networks:
  #     - proxynet
##### END - Simple Simulator Apps & Services #####

##### BEGIN - TimescaleDB Service #####
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12-oss
    restart: always
    environment: 
      - POSTGRES_USER=timescaledb
      - POSTGRES_PASSWORD=p0stgr3ss
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./timescale-sql:/var/lib/postgresql
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    logging: *default-logging
    networks:
      - proxynet
##### END - TimescaleDB Service #####
