version: "3.9"

x-logging: &default-logging
  options:
    max-size: "5m"
    max-file: "5"
  driver: json-file

services:
    timescaledb:
        container_name: timescaledb
        image: timescale/timescaledb:latest-pg12-oss
        restart: always
        environment: 
          - POSTGRES_PASSWORD=p0stgr3s
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql
          # copy the sql script to create tables
          # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          # copy the sql script to fill tables
          # - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
